'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddressGeoCode_DataEntry

    '''<summary>
    '''updAddresses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updAddresses As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''AddressDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddressDataEntry As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Search_Addresses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Search_Addresses As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''txtSearchAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSearchCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSearchState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSearchZIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchZIP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSearchMatchStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchMatchStatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSearchMatchSubStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchMatchSubStatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tblSearchAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblSearchAddress As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Update_Addresses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Update_Addresses As Global.System.Web.UI.WebControls.GridView
End Class
