'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WFPPS

    '''<summary>
    '''ScriptManagerProxy1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManagerProxy1 As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''WFPPSTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WFPPSTabs As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tpWFSubmissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpWFSubmissions As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''updMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updMain As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lbOpenWFPPSInst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbOpenWFPPSInst As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''A2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblDepositDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDepositDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSubmitTheBag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitTheBag As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnreset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnreset As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtDepositBag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepositBag As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDepositSlip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepositSlip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDepositTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDepositTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlDepositLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDepositLoc As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''MainTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''txtDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet7 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree7 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet8 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree8 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet9 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree9 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet10 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree10 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet11 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree11 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet12 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree12 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet13 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree13 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet14 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree14 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet15 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree15 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet16 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree16 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate17 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet17 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash17 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual17 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree17 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain17 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate18 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet18 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash18 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual18 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree18 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain18 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate19 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet19 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash19 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual19 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree19 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain19 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate20 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet20 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash20 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual20 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree20 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain20 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate21 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet21 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash21 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual21 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree21 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain21 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate22 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet22 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash22 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual22 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree22 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain22 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate23 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet23 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash23 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual23 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree23 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain23 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate24 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet24 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash24 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual24 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree24 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain24 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate25 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOutlet25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutlet25 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCash25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCash25 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManual25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManual25 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotal25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAgree25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgree25 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExplain25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplain25 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FakeButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FakeButton As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''explantionlabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents explantionlabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnOptInstructions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOptInstructions As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PrintButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrintButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''OkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OkButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblHoldOverSQL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHoldOverSQL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHoldOverrows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHoldOverrows As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ModalPopupExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtender1 As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''tpAdminReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpAdminReject As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlFilterEntity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFilterEntity As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlFilterLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFilterLocation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlFilterSubmitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFilterSubmitter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtFilterDepBagNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFilterDepBagNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFilterDepSlipNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFilterDepSlipNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDDStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDDStartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtDDEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDDEndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender2 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''ScrollPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvSubmittedBags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSubmittedBags As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblSelectBagID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectBagID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSelectBagDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectBagDD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSelectBagDepNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectBagDepNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSelectBagDepSlip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectBagDepSlip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSelectTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSelectSubBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectSubBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlScrollPanelSelectedBag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlScrollPanelSelectedBag As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvSelectedBag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSelectedBag As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtRejectReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRejectReason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnRejectBag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRejectBag As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FakeButton3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FakeButton3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ExplanationLabelReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExplanationLabelReject As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnMPROK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMPROK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMPRCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMPRCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMPRnvm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMPRnvm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtenderReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderReject As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''tpSuperAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpSuperAdmin As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlSAEntity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSAEntity As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSALoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSALoc As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSASubBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSASubBy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSADepBag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSADepBag As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSADepSlip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSADepSlip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSAStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSAStartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender3 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtSAEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSAEndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender4 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvSABags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSABags As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblSABagID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSABagID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSADepDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSADepDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSADepBagNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSADepBagNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSADepSlipNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSADepSlipNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSADepBagTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSADepBagTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSASubBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSASubBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvSARows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSARows As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtSARejectReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSARejectReason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSAUpdateBag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSAUpdateBag As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSARejectReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSARejectReason As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FakeButtonSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FakeButtonSA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''mpeSAexplanationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeSAexplanationLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpeSAOKButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeSAOKButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeSACancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeSACancelButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeSA As Global.AjaxControlToolkit.ModalPopupExtender
End Class
