'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RadOHMS_Administrative

    '''<summary>
    '''ScriptManagerProxy1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManagerProxy1 As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''FlashMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlashMessages As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Add_UserIDPermissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Add_UserIDPermissions As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FetchUserPermissions_Btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FetchUserPermissions_Btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SelectAllLocations_Btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectAllLocations_Btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbSrchUsr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSrchUsr As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlSrchUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSrchUser As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtAdminUsrSrch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdminUsrSrch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAdminUsrSrch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdminUsrSrch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbCloseUsrSrch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCloseUsrSrch As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''updateProgressSearching control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updateProgressSearching As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''lblAdminUsrResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdminUsrResults As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ListPermissionLocations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListPermissionLocations As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Locations_SelectedUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Locations_SelectedUser As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UserLocations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserLocations As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Locations_Field control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Locations_Field As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SubmitPermissionChanges_Btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitPermissionChanges_Btn As Global.System.Web.UI.WebControls.Button
End Class
