'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ImageReview

    '''<summary>
    '''ScriptManagerProxy1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManagerProxy1 As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''ARActivityReportTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ARActivityReportTabs As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''TechRoster_Tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TechRoster_Tab As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''TechRoster_UpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TechRoster_UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlManageDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlManageDepartments As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TechNames_Gridview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TechNames_Gridview As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''AddRemoveUsers_Btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddRemoveUsers_Btn As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''AddRemoveUser_Modal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddRemoveUser_Modal As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''AddRemoveUser_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddRemoveUser_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''AddRemoveUser_CloseBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddRemoveUser_CloseBtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AddRemoveUser_Submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddRemoveUser_Submit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''YourTechRoster_Gridview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YourTechRoster_Gridview As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pendingrosterchanges_ul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pendingrosterchanges_ul As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pendingrosterchanges_hidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pendingrosterchanges_hidden As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''applypendingchanges_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents applypendingchanges_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ImageEvaluations_Tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageEvaluations_Tab As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''ImageEvaluations_UpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageEvaluations_UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''YourTechs_Gridview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YourTechs_Gridview As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''AccessionIDs_UL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccessionIDs_UL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''EvalFacility_DDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EvalFacility_DDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ImageForm_Accession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageForm_Accession As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Eval_Submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Submit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShow As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SuccessFailure_Modal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SuccessFailure_Modal As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''SuccessFailure_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SuccessFailure_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SuccessFailure_CloseBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SuccessFailure_CloseBtn As Global.System.Web.UI.WebControls.Button
End Class
