<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="LookupTableEditor.aspx.vb" Inherits="FinanceWeb.LookupTableEditor" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="FeaturedContent" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="MainContent" runat="server">

         <asp:ScriptManagerProxy ID="ScriptManagerProxy1" runat="server">
    </asp:ScriptManagerProxy>

    <script>

        function open_win() {
            window.open("https://financeweb.northside.local/Tools/MD/udMDPOSDescMappingInstructions.aspx", "MDPOSDescMappingInstructions", "height=768,width=800, scrollbars, resizable");
        }
        
    </script>

       <cc1:tabcontainer ID="tcLUTableEditor" runat="server"
            ActiveTabIndex = "0" UseVerticalStripPlacement = "False" width="1150px" >
                    <cc1:TabPanel runat = "server" HeaderText = "Lookup Table Editor" ID = "tpLUTableMain" >
                    <ContentTemplate>    
<asp:UpdatePanel runat="server" ID= "updMain" ><ContentTemplate>
      <asp:Panel runat = "server" HorizontalAlign = "Right" > <asp:Button ID="lbOpenLUTableInst" runat="server" Visible="false" Text="Open Instructions"  OnClientClick="open_win()"  /> </asp:Panel>
    <br />
                            <asp:Table runat="server" Width="100%">
                            <asp:TableRow>
                                <asp:TableCell>
<asp:Label ID="tableLabel" runat = "server" Font-Bold = "true" Font-Size = "small" ForeColor = "#4A8fd2" >
    Select Table:&nbsp;&nbsp;&nbsp;</asp:Label>
                                </asp:TableCell>
                                <asp:TableCell></asp:TableCell>
                                <asp:TableCell>
        <asp:DropDownList ID="ddlSelectedTable" runat="server" AutoPostBack = "true"
            AppendDataBoundItems="False" Font-Size = "small">
                    </asp:DropDownList>
                                </asp:TableCell>
                                <asp:TableCell></asp:TableCell>
                                <asp:TableCell HorizontalAlign="Right">
                                    <asp:Button runat="server" Visible="false" Text="Export Selected Table" ID="btnExportLUTable" /><br />
                                </asp:TableCell>
                            </asp:TableRow>
                        </asp:Table>

    <asp:Panel runat ="server" ScrollBars="Auto" Width ="1000px" Height="600px" >

                                
                                 <asp:GridView runat="server" ShowHeaderWhenEmpty ="true"  ID="gvLUTable" AutoGenerateColumns="true" 
                                  BackColor="#CBE3FB" AllowPaging="true" CellSpacing ="5" HeaderStyle-Font-Size ="Smaller"
                                 AllowSorting="true" PageSize="50" Font-Size="Small" AutoGenerateEditButton="True" AutoGenerateDeleteButton ="true"
                                  HeaderStyle-BackColor="#4A8fd2" HeaderStyle-ForeColor="White" CellPadding="5">
                                 <AlternatingRowStyle BackColor="white" />
                             </asp:GridView>

        </asp:Panel>
    </ContentTemplate>
                              <Triggers>

          <asp:PostBackTrigger ControlID ="btnExportLUTable" /> 
          
 </Triggers>
    </asp:UpdatePanel>
                        </ContentTemplate>
                        </cc1:TabPanel>
           </cc1:tabcontainer>
</asp:Content>
