'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LookupTableEditor

    '''<summary>
    '''ScriptManagerProxy1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManagerProxy1 As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''tcLUTableEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tcLUTableEditor As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tpLUTableMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpLUTableMain As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''updMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updMain As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lbOpenLUTableInst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbOpenLUTableInst As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tableLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tableLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlSelectedTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSelectedTable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnExportLUTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportLUTable As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvLUTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvLUTable As Global.System.Web.UI.WebControls.GridView
End Class
