'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OHMSRADDataEntry

    '''<summary>
    '''ScriptManagerProxy1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManagerProxy1 As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''OhmsAdminTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OhmsAdminTabs As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tpXRData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpXRData As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''updMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updMain As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LocatioinRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocatioinRow As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''ddlLocationSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLocationSelect As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlXIVFYQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlXIVFYQ As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''gvXRayImagingViews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvXRayImagingViews As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnSubmitObservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitObservation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FakeButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FakeButton2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''explanationlabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents explanationlabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OkButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OkButton2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtender As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''tpXRayMRI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpXRayMRI As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''updatePanelMRIXRAY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatePanelMRIXRAY As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlLocation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLocation2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlModality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlModality As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlRRFYQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRRFYQ As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbchangeDate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbchangeDate2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HideIfMRI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HideIfMRI As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''ddlRRWeekSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRRWeekSelect As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbChangeDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbChangeDate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblRRFakeWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRRFakeWeek As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvRR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRR As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvRRTotalExposures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRRTotalExposures As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnRepeatSubmission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRepeatSubmission As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FakeButtonRR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FakeButtonRR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelRR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelRR As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ExplanationLabelRR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExplanationLabelRR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnOKAYRR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOKAYRR As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRRConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRRConfirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtenderRR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderRR As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''FakeCorrectDatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FakeCorrectDatePanel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlModalPopupWrongDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlModalPopupWrongDate As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCorrectDateFYQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCorrectDateFYQ As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCorrectDateWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCorrectDateWeek As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblFakeCorrectWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFakeCorrectWeek As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnCorrectDateConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCorrectDateConfirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCorrectDateCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCorrectDateCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupWrongDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupWrongDate As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''tpHandHygiene control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpHandHygiene As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''UpdatePanelHH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelHH As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''HHPanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HHPanel3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlHHLocationSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHHLocationSelect As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEntryDateSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEntryDateSelect As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ScrollPanelgvSubmitData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollPanelgvSubmitData As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvSubmitData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSubmitData As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnHHUpdateRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHHUpdateRows As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FakeButtonHH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FakeButtonHH As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelHH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelHH As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ExplanationLabelHH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExplanationLabelHH As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonHH3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonHH3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtenderHH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderHH As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''FakeButtonHH2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FakeButtonHH2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelHHPageChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelHHPageChange As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ExplanationLabelHHPC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExplanationLabelHHPC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SubmitButtonHHPageChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButtonHHPageChange As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnChangePage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChangePage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CancelButtonHHPageChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButtonHHPageChange As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hiddenLblpass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenLblpass As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ModalPopupExtenderHH2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderHH2 As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''tpRadiologyBonfire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpRadiologyBonfire As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''upRadiology Bonfire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upRadiologyBonfire As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Panel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlBonfireLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBonfireLocation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''gvBonfire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvBonfire As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnSubmitBonfire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitBonfire As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblBonfireFakeBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBonfireFakeBtn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlBonfirePopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBonfirePopup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblBonfireExceptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBonfireExceptions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnOkayBonfireModalPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOkayBonfireModalPopup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeBonfirePopups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeBonfirePopups As Global.AjaxControlToolkit.ModalPopupExtender
End Class
