'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NZ_DataDictionary

    '''<summary>
    '''ScriptManagerProxy1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManagerProxy1 As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''updMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updMain As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlDD_Tables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDD_Tables As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnLoadData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLoadData As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ReturntoSchemaBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReturntoSchemaBtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ReturntoTablesBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReturntoTablesBtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DDExcelLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDExcelLink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Update_Schema control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Update_Schema As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''PanelTables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelTables As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Search_tbls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Search_tbls As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tbl_SearchSchemas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_SearchSchemas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbl_SearchTables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_SearchTables As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Tables_Srch_RadioBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tables_Srch_RadioBtn As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''tbl_tblTSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_tblTSelect As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Tables_EmptyFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tables_EmptyFilter As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Update_Tables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Update_Tables As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''PanelColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelColumns As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SearchColumnDatatbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchColumnDatatbl As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''Cols_SearchID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cols_SearchID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Cols_SearchColumnName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cols_SearchColumnName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Columns_Srch_RadioBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Columns_Srch_RadioBtn As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''ColumnData_AddRow_Btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ColumnData_AddRow_Btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Columns_EmptyFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Columns_EmptyFilter As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Update_Columns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Update_Columns As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''PanelMapping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelMapping As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SearchMappingtbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchMappingtbl As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''txtTblSearchID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTblSearchID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTblSearchSchemaName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTblSearchSchemaName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTblSearchTableName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTblSearchTableName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTblSearchColumnName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTblSearchColumnName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Mapping_Srch_RadioBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Mapping_Srch_RadioBtn As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''tblTSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblTSelect As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Update_Mapping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Update_Mapping As Global.System.Web.UI.WebControls.GridView
End Class
